#server port settings
server:
  port: 8000

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=UTC&useSSL=false
    username: jeongwon
    password: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false
    show-sql: true    properties:
      hibernate.format_sql: true
    
    security:
      oauth2:
        client:
          registration:
            kakao:
              client-id:  4c2495a3f19c8aa9c9942bd87ca19fa8
              client-name: Kakao
              redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
              scope: profile_nickname, account_email
              authorization-grant-type: authorization_code
              client-authentication-method: POST
              
          provider:
            kakao:
              authorization_uri: https://kauth.kakao.com/oauth/authorize
              token_uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user_name_attribute: id
              
#log level settings
logging:
  level:
    root: info