#server port settings
server:
  port: 8000

spring:

  datasource:
    driver-class-name: ENC(Exn1HtBHYTsjGwNou8uY2xHGOLDqN+g3KjG9cJOYJcwrG0OpIL8sBA==)
    url: ENC(QdSwGP0H9y8T9oKHwxPhxq3bLf5kYr5YD2+AWCnfFOPRB1QBNQDXmEoWkO1iebRZlCEy7HPE6Aa9WCTi6i7Ln3IWD5XHDp2XHhoG2Ly2XJE=)
    username: ENC(evrGsTrRWDYdxA80AGiTVpqiy4N5XHmk)
    password: ENC(IS9Hr4GT0DJtG4REYaJV4Q==)

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false
    show-sql: true    properties:
      hibernate.format_sql: true
    
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:  ENC(7iV8zSDyHPgiPs0IrSIgoTo//zbzzlM9IxMQ6PZXT9ZBdGoVtM9uezgI54N3NQ1P)
            client-name: Kakao
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
          
          naver:
            client-id: ENC(QxTTQOW2aU0Y9nPTXyn99G7J8sUIbbJxWfBRTrS6Tic=)
            client-secret: ndDlD5htaJ
            client-name: Naver
            scope: email, nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
            client-authentication-method: POST
          
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        
#log level settings
logging:
  level:
    root: info
    
#site properties
site:
  name: shop